wandb_version: 1

LR:
  desc: null
  value: 0.00035
NUM_ENVS:
  desc: null
  value: 48
NUM_STEPS:
  desc: null
  value: 256
TOTAL_TIMESTEPS:
  desc: null
  value: 7500000.0
UPDATE_EPOCHS:
  desc: null
  value: 4
NUM_MINIBATCHES:
  desc: null
  value: 4
GAMMA:
  desc: null
  value: 0.99
GAE_LAMBDA:
  desc: null
  value: 0.95
CLIP_EPS:
  desc: null
  value: 0.2
SCALE_CLIP_EPS:
  desc: null
  value: false
ENT_COEF:
  desc: null
  value: 0.01
VF_COEF:
  desc: null
  value: 0.5
MAX_GRAD_NORM:
  desc: null
  value: 0.5
ACTIVATION:
  desc: null
  value: tanh
ENV_NAME:
  desc: null
  value: overcooked
LAYOUTS:
  desc: null
  value:
  - cramped_room
  - asymm_advantages
ANNEAL_LR:
  desc: null
  value: true
SEED:
  desc: null
  value: 0
NUM_SEEDS:
  desc: null
  value: 3
WANDB_MODE:
  desc: null
  value: online
ENTITY:
  desc: null
  value: thichqwerty
PROJECT:
  desc: null
  value: r2i_mappo_overcooked
rssm:
  desc: null
  value:
    deter: 4096
    units: 1024
    hidden: 128
    stoch: 32
    classes: 32
    act: silu
    norm: layer
    initial: learned
    unimix: 0.01
    unroll: true
    action_clip: 1.0
    winit: normal
    fan: avg
    nonrecurrent_enc: false
ssm:
  desc: null
  value:
    n_layers: 2
    prenorm: false
    mlp: true
    glu: true
    dropout: 0.0
    parallel: true
    conv: false
    use_norm: true
ssm_cell:
  desc: null
  value:
    reset_mode: init
    n_blocks: 8
    C_init: trunc_standard_normal
    conj_sym: false
    discretization: bilinear
    clip_eigs: false
    dt_min: 0.001
    dt_max: 0.1
ssm_type:
  desc: null
  value: mimo
_wandb:
  desc: null
  value:
    python_version: 3.12.3
    cli_version: 0.17.4
    framework: keras
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1722352278
    t:
      1:
      - 2
      - 3
      - 12
      - 45
      - 50
      - 55
      2:
      - 2
      - 3
      - 12
      - 45
      - 50
      - 55
      3:
      - 13
      - 15
      - 16
      - 23
      4: 3.12.3
      5: 0.17.4
      8:
      - 5
      13: linux-x86_64
