# # For comparison with r2i
# "LR": 3.5e-4
# "NUM_ENVS": 48
# "NUM_STEPS": 256
# "TOTAL_TIMESTEPS": 7.5e+6

"LR": 3.5e-4
"NUM_ENVS": 128
"NUM_STEPS": 512
"TOTAL_TIMESTEPS": 7.0e+7
"UPDATE_EPOCHS": 4
"NUM_MINIBATCHES": 4
"GAMMA": 0.99 
"GAE_LAMBDA": 0.95 
"CLIP_EPS": 0.2 
"SCALE_CLIP_EPS": False
"ENT_COEF": 0.01
"VF_COEF": 0.5 
"MAX_GRAD_NORM": 0.5
"ACTIVATION": "tanh"
"ENV_NAME": "overcooked"
"SR": "yes"

"LAYOUTS": ["cramped_room", "asymm_advantages", "coord_ring", "forced_coord", "counter_circuit"]
# "LAYOUTS": ["asymm_advantages"]
"ANNEAL_LR": True 
"SEED": 0
"NUM_SEEDS": 3

# WandB Params
"WANDB_MODE": "online"
"ENTITY": "thichqwerty"
"PROJECT": "r2i_mappo_overcooked"
